# Generated by Django 3.1.7 on 2021-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211019_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='question1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='question2',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
